### ISSUE TITLE
Problem with package 

### ISSUE THREAD

**Issue by erdgrau** [yoolab/iron-router-i18n#63] opened 2015-06-14 17:05 UTC
Hi!
I added your package in my project, but I have some problems.
## versions: 

martino:iron-router-i18n@1.0.2
martino:i18n-conf@0.3.1 - I added it manually, because "meteor add martino:iron-router-i18n" doesn't add  itself this package.
meteor@1.1.6
meteor-platform@1.2.2
## config: lib/router/config.js

I18NConf.configure({
    defaultLanguage: 'ru',
    languages: ['en', 'uk', 'ru'],
    autoConfLanguage: false
});

Router.configure({
    notFoundTemplate: 'notFound',

```
i18n: {
    langCodeForDefaultLanguage: true,
    exclude: {
        admin_paths: '^\/admin'
    }
}
```

});
## my example rout: lib/router/user/contact.js

Router.route('/contact', {
    name: 'contact',
    template: 'contact',
    layoutTemplate: 'application',
    action: function() {
        this.render();  
    }
});

So, in rout /contact I have page 404 at address http://localhost:3000/ru/contact - why ?
## In browser console this:

Exception from Tracker afterFlush function:
debug.js:41 TypeError: Cannot read property 'path' of undefined
    at Function.Router.getLangCode (router.js:402)
    at setLngClass (header.js?849b45df8e432333026facae3b558c5b95534e65:26)
    at null.<anonymous> (header.js?849b45df8e432333026facae3b558c5b95534e65:12)
    at template.js:116
    at Function.Template._withTemplateInstanceFunc (template.js:437)
    at fireCallbacks (template.js:112)
    at null.<anonymous> (template.js:205)
    at view.js:104
    at Object.Blaze._withCurrentView (view.js:523)
    at view.js:103
## Then helper {{pathFor 'contact' }} - doesn't work for languages 'ru' and 'uk'. In console (browser), I have this: 

Exception in template helper: TypeError: Cannot read property 'handler' of undefined
    at Function.Iron.Route.path (http://localhost:3000/packages/martino_iron-router-i18n.js?74afba74b3d758a03bb957b9d8c4f2cc9190d645:627:17)
    at Object.<anonymous> (http://localhost:3000/packages/martino_iron-router-i18n.js?74afba74b3d758a03bb957b9d8c4f2cc9190d645:724:22)
    at bindDataContext (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2880:16)
    at Blaze._wrapCatchingExceptions (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1651:16)
    at http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2928:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3476:12)
    at wrapHelper (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2927:27)
    at Spacebars.call (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:172:18)
    at Spacebars.mustacheImpl (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:109:25)
    at Object.Spacebars.mustache (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:113:39)

But, helper {{pathFor 'contact'}}, perfectly works for language 'en', and I have valid page with route (browser)  - http://localhost:3000/en/contact

P.S. My OS Windows 8.1

**Comment by martinopic** [comment] 2015-07-07 14:19
Sorry for the late reply, this could be something related to https://github.com/yoolab/iron-router-i18n/issues/64 I'll commit a patch soon, please keep an eye on that issue and tell me if it also solve your problem.

**Comment by erdgrau** [comment] 2015-07-10 20:53
I cloned repository and set in console 'meteor add martino:iron-router-i18n', then I had version martino:iron-router-i18n@1.0.4. But now I have the same problem with helper {{pathFor}}. Mb is it my fault? 

My example is config:
I18NConf.configure({
    languages: ["ru", "uk", "en"],
    defaultLanguage: 'ru',
    autoConfLanguage: true
});

Router.configure({
    notFoundTemplate: 'notFound',
    i18n: { 
        langCodeForDefaultLanguage: false,

```
    exclude: {
        admin_paths: '^\/admin'
    }
}
```

});

My example is rout contact:
Router.route('/contact', {
    name: 'contact',
    template: 'contact',
    layoutTemplate: 'application',
    action: function() {
        this.render();
        }
}

This is a fucntion which changes language:
'click .lang-change': function(e) {
        var lng = e.target.id; // uk - string
        I18NConf.setLanguage(lng);
}

this is an example, where I use helper {{pathFor}}:
  <//li> <//a href="{{pathFor 'contact'}}"> **********\* <///a> <///li>

![ggfgf](https://cloud.githubusercontent.com/assets/12447113/8628973/d9875e82-275f-11e5-897f-6c29e1bd7baa.jpg)

**Comment by martinopic** [comment] 2015-07-10 22:49
I've tested your configuration with simple app you find in `examples/basic`, with the code you find below and `pathFor` seems to work perfectly. I need to replicate the problem could you please prepare me a toy app that shows the problem?

init.js:

``` javascript
I18NConf.configure({
    languages: ["ru", "uk", "en"],
    defaultLanguage: 'ru',
    autoConfLanguage: true
});

Router.configure({
    notFoundTemplate: 'notFound',
    layoutTemplate: 'layout',
    i18n: {
        langCodeForDefaultLanguage: false,

        exclude: {
            admin_paths: '^\/admin'
        }
    }
});

Router.route('/contact', {
    name: 'contact',
    template: 'contact',
    action: function () {
        this.render();
    }
});

Router.route('/one');
Router.route('/two');
Router.route('/three');
```

basic.html

``` html
<template name="layout">
    <head>
        <title>Iron Router i18n - Basic Sample</title>
    </head>
    <body>
    <header>
        <ul class="langMenu">
            <li><a id="ru" href="#">RU</a></li>
            <li><a id="uk" href="#">UK</a></li>
            <li><a id="en" href="#">EN</a></li>
            <li><strong>Current language: </strong>{{ currentLanguage }}</li>
        </ul>
    </header>
    {{> yield}}
    </body>

</template>

<template name="Home">
    {{> Nav}}

    <h1>Home</h1>

    <p>
        Data Title: {{title}}
    </p>
</template>

<template name="One">
    {{> Nav}}

    <h1>Page One</h1>
</template>

<template name="Two">
    {{> Nav}}

    <h1>Page Two</h1>
</template>

<template name="contact">
    {{> Nav}}

    <h1>Page Contact</h1>
</template>

<template name="Nav">
    <ul>
        <li>
            <a href="{{pathFor 'contact'}}">Contact</a>
        </li>
        <li>
            <a href="{{pathFor 'one'}}">Page One</a>
        </li>
        <li>
            <a href="{{pathFor 'two'}}">Page Two</a>
        </li>
    </ul>
</template>
```

basic.js:

``` javascript
Template.layout.events({
    'click .langMenu > li > a': function (event, template) {
        I18NConf.setLanguage(event.target.id);
        event.preventDefault();
    }
});

Template.layout.helpers({
    currentLanguage: function () {
        I18NConf.languageDep.depend();
        return I18NConf.getLanguage();
    }
});
```

**Comment by erdgrau** [comment] 2015-07-11 10:06
I think, I have solved this problem. 

There is my structure:
![11111as](https://cloud.githubusercontent.com/assets/12447113/8633333/9a7fc85c-27cb-11e5-9b76-0af13b012bcf.jpg)

Threre is config.js:
I18NConf.configure({
...
})
Router.configure({
...
})

My routes are in different files and folders. So, I added my routes, like your examples, and got valid helper {{pathFor}}. My structure works perfectly with original iron:router. It is strange problem, I think.

**Comment by martinopic** [comment] 2015-07-11 16:31
You're right, that's an interesting case. It's probably due to the Meteor file load order logic and the way you structured your code: when you create an i18n route the route is created depending on the current router i18n configuration but if the configuration is loaded and executed AFTER the route has been created there come the problem.

In order to keep some kind of structure but still load first all i18n Router configuration you should follow the [Meteor rules for scripts load order](http://docs.meteor.com/#/full/structuringyourapp) and maybe place the router configuration in some "lib" directory and routes outside "lib" directories.

Anyway I understand this is a weird limitation due to the same design of iron-router-i18n so I'm also thinking about a potential fix for this which could be delaying adding routes (i18n and not) to the startup phase. Strange nobody came up with this before :-)

**Comment by martinopic** [comment] 2015-07-14 13:13
I've created a mechanism to defer route creation on Meteor.startup in order to avoid possible problems due to file load order like the one you reported. As I'm still unsure on whether how to release it I'd be grateful if you could test it on your configuration and see if it solve the problem. I've also added an automated test for this but it's a relatively big change in logic and I want to test it a bit more before release.

In order to test it please download and use https://github.com/yoolab/iron-router-i18n/tree/issue-63 branch.

**Comment by erdgrau** [comment] 2015-07-14 14:59
I cloned your branch 'iron-router-i18n-issue-63' and I tested it in my project. It works perfectly. Thanks a lot.

**Comment by martinopic** [comment] 2015-07-14 17:58
Version 1.1.0 now defer route creation to `Meteor.startup` phase. As this is a relatively big change in inner logic there is also a new option to disable the new default behaviour. Anyway the new inner working should be safe (I'd say safer) 99,9% of the times.

**Comment by richarddewit** [comment] 2015-07-24 07:14
Please flag this a **"breaking change"** update! Spent 2 hours trying to figure out why this update broke my code...

**lib/config.coffee**

``` coffeescript
Router.configure
  i18n: {
    deferRouteCreation: false
  }
```

**Comment by martinopic** [comment] 2015-07-24 10:40
Sorry about that. Before pushing the change I thought a bit about how could this be a breaking change but I really couldn't figure out a case where deferring route creation to meteor startup could be a problem. Could you please explain me exactly how this is affecting your configuration?

A different approach could be to regenerate all routes on every `Route.configure` having to do with i18n or maybe just leaving "deferRouteCreation" default to false. But I need to understand better which cases this is affecting.

**Comment by richarddewit** [comment] 2015-07-24 12:01
I'm not quite sure what exactly causes this, so I'll try to capture everything related.

When I omit the `deferRouteCreation: false` (it being true by default), Iron Router doesn't recognize my routes, and:
- **iron-router-i18n** throwing `TypeError: Cannot read property '_i18n' of undefined` when I use `pathFor`
- **Iron Router** logging a warning saying `pathFor couldn't find a route named "products"` 
- **Iron Router** showing my `notFoundTemplate`.

The error is referring to line 3 of **packages/martino:iron-router-i18n/lib/router_controller_client.js**:

``` js
RouteController.prototype.lookupTemplate = function () {                                                      // 1
    return this.lookupOption('template') ||                                                                   // 2
        (this.router && this.router.toTemplateName(this.route._i18n.defaultRoute.getName()));                 // 3
};                                                                                                            // 4
```

Iron Router does load it's global configuration (`Router.configure`) though. The `layoutTemplate`, `loadingTemplate`, `notFoundTemplate`, etc are correctly used.

When removing `martino:iron-router-i18n` and going to the normal, non-localized routes (e.g. `/products`) the routes are functioning properly, but re-adding it, breaks it again.

I also tried wrapping my routes in `Meteor.startup`, but without success.

I declare routes in **lib/routes.coffee** as follows:

``` coffeescript
Router.route "/products",
  name: "products"
  waitOn: ->
    Meteor.subscribe("products")
```

(Plain JS)

``` js
Router.route("/products", {
  name: "products",
  waitOn: function() {
    Meteor.subscribe("products")
  }
});
```

All is fixed when I include `deferRouteCreation: false` in `Router.configure`'s `i18n` option.

I hope to have provided enough details. If not, do ask for more.

**Comment by martinopic** [comment] 2015-07-25 21:41
Thanks a lot for the information quite useful but I really can't reproduce the problem, the ideal thing would be a toy application reproducing the problem.

In any case I've tried a different approach where routes are recreated on each `Router.configure` call with an i18n section. In addition to solve the original problem (issues caused by meteor file load order logic) this could be also useful for edge cases like dinamically configure i18n.

I'd be very grateful if you could test the following branch with your application and tell me if it works (no need for any configuration change). The issue you reported shows it's something difficult to test (in my idea wasn't a breaking change just a relatively big inner implementation change)

https://github.com/yoolab/iron-router-i18n/tree/issue-63

**Comment by martinopic** [comment] 2015-08-14 16:51
Version 1.2.0 should solve ay problem related to this as it will change the internal implementation (see #69)

**Comment by martinopic** [comment] 2015-08-16 20:13
Version 1.2.0 has been published, I've added several tests regarding "on the fly reconfiguration" which is the feature related to this original problem (problems caused by load file order) and improves very much the original internal implementation that could have caused other weird problems reported in this bug. 

Feedback will be appreciated :-)

**Closed as completed** 2015-12-17 21:44 UTC
Labels: bug, enhancement
